datasets:
  mnist: ./datasets/mnist/data

train:
  seed: 1770023300
  model: mnist32
  dataset: mnist

  batch_size: 128
  epochs: 200
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0
  schedule: 
    type: cosineWR
    T0: 10
    T_mult: 2

  checkpoints_dir: /media/solis/DATA/Santripta/AETraining/checkpoints/
  tensorboard_dir: /media/solis/DATA/Santripta/AETraining/tensorboard/

infer:
  output_dir: /media/santripta/data2/AEInference/landscape_data

  collect:
    - path: decoder.fc
      tag: latents

  epochs:
    - all

name: mnist
device: cuda:1