datasets: 
  imagenet: /media/solis/DATA/imagenet

do:
  # - vgg_imagenet
  # - densenet_imagenet
  - resnet_imagenet
  - wres_imagenet

config:
  tensorboard_dir: /media/solis/DATA/Santripta/Training_imagenet/tensorboard
  checkpoint_dir: /media/solis/DATA/Santripta/Training_imagenet/checkpoints
  experiments_dir: ./training-inference/train_runs_imagenet
  device: cuda:1