datasets: 
  cifar10: ./datasets/cifar10/data
  mnist: ./datasets/mnist/data

do:
  - densenet_cifar
  - densenet_mnist
  - resnet_cifar
  - resnet_mnist
  - vgg_cifar
  - vgg_mnist
  - wres_cifar
  - wres_mnist

config:
  tensorboard_dir: C:/home/llvis/model_training/tensorboard
  checkpoint_dir: C:/home/llvis/model_training/checkpoints
  device: cuda