datasets: 
  cifar: ./datasets/cifar/data
  mnist: ./datasets/mnist/data

do:
  - densenet_cifar
  - densenet_mnist
  - resnet_cifar
  - resnet_mnist
  - vgg_cifar
  - vgg_mnist
  - wres_cifar
  - wres_mnist

config:
  tensorboard_dir: /media/solis/DATA/Santripta/Training/tensorboard
  checkpoint_dir: /media/solis/DATA/Santripta/Training/checkpoints
  experiments_dir: ./training-inference/train_runs
  device: cuda