runs:
  vgg_cifar:
    seed: 1759764288
    dataset: cifar
    lr: 0.01

  vgg_mnist:
    seed: 1759764291
    lr: 0.0001
    dataset: mnist

model: vgg16
batch_size: 128
epochs: 200
lr: 0.001
momentum: 0.9
weight_decay: 0.0